<a href="https://colab.research.google.com/github/Dhatrikowthavarapu/reponew/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
n=list(map(str,input("enter number:").split(" ")))
s=0
for i in n:
  x=int(i[1]) 
  s+=x
print(s)

enter number:123 456
7


Types of Data in realtime 

1.Quantitative 
   - Represents the size/volume of data
     - Discrete and Continuous
        - This type of Data is fixed/constant
           - ex numbers on dievaries from 1 to 6
      -Distance ,colour,nationality,size etc
          - Contionuous data means the value/data is continuous
           - height,weight & hours
2.Qualitative
  - Data is Observed and placed in terms of category
    - Ex:Data submission in feedback form 

Data in Stastics 
  - Nominal,ordinal,Interval and Ratio
    - Nominal means data is Categorised on the basis of names
      - Ex:Natiopnality,Colour,Gender.
    - Ordinal means data is based upon the order of values.
      - Feedback form
    - Interval means a range of data Values.
      - Time interval in clock 2:15 is in b/w 2&3

importing module
  - Numpy
  - Pandas
  - Matplotlib and Seaborn

In [ ]:
import numpy as np
dir(np)                     #directory of numpy

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_

In [ ]:
np.__version__

'1.19.5'

### Numpy
- Numpy stands for NumericalPython
- Which is used to deal with array type of data,Scientific Computation


### Array creation()
- array() is the submodule in Numpy module
- np.array(iterable)

In [ ]:
print(np.array([1,22,3,4,5]))
print(np.array(1))

[ 1 22  3  4  5]
1


In [ ]:
print(np.array((1,22,3,4,5),dtype="float"))

[ 1. 22.  3.  4.  5.]


In [ ]:
a=np.array([1.21,2.2,3.0,4.8,5.4],dtype="int")
print(a)

[1 2 3 4 5]


In [ ]:
a=np.array([1.21,2.2,3.0,4.8,5.4],dtype="str")
print(a)

['1.21' '2.2' '3.0' '4.8' '5.4']


In [ ]:
print(np.array((1,22,3,4,5),dtype="str"))

['1' '22' '3' '4' '5']


In [ ]:
print(np.array(n,dtype="int"))

[123 456]


In [ ]:
n

['123', '456']

In [ ]:
print(np.array(range(10, 90,5)))

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85]


In [ ]:
print(np.array(range(90, 10,-5)))

[90 85 80 75 70 65 60 55 50 45 40 35 30 25 20 15]


## 2D Arrays

In [ ]:
l=np.array(([1,2,4],[3,4,6]),dtype="float")
print(l)

[[1. 2. 4.]
 [3. 4. 6.]]


In [ ]:
l.size

6

In [ ]:
l.shape

(2, 3)

In [ ]:
l.dtype

dtype('float64')

In [ ]:
l.itemsize # size of each item

8

In [ ]:
#3d Arrays

In [ ]:
d=np.array([[1,2,3],[3,5,6],[6,7,8]])
print(d)

[[1 2 3]
 [3 5 6]
 [6 7 8]]


In [ ]:
d[0]

array([1, 2, 3])

In [ ]:
d[1]

array([3, 5, 6])

We can creat 32 Dimensional arrays

In [ ]:
t=np.array([[1,2,3],[3,4,5]],ndmin=3)
t

array([[[1, 2, 3],
        [3, 4, 5]]])

In [ ]:
t.ndim #(no,row,col)

3

In [ ]:
t=np.array([1,2,3],ndmin=32)
t

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1, 2,
                                      3]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [ ]:
# identity matrix
x=np.eye(4,5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [ ]:
# zeros in rows
z=np.zeros(3)
z

array([0., 0., 0.])

In [ ]:
x=np.eye(4)
x


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# zeros in rows
z=np.zeros((3,1))
z

array([[0.],
       [0.],
       [0.]])

In [ ]:
y=np.ones(4)
y

array([1., 1., 1., 1.])

In [ ]:
y=np.ones((4,2),dtype="int")
y

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
y=np.ones((2,4),dtype="str")
y

array([['1', '1', '1', '1'],
       ['1', '1', '1', '1']], dtype='<U1')

In [ ]:
y=np.ones((4,2,4),dtype="int")
y

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [ ]:
f=np.full((3,2),"Dhatri")
f

array([['Dhatri', 'Dhatri'],
       ['Dhatri', 'Dhatri'],
       ['Dhatri', 'Dhatri']], dtype='<U6')

In [ ]:
f.fill(4)
f

array([['4', '4'],
       ['4', '4'],
       ['4', '4']], dtype='<U6')

In [ ]:
f.fill("hey")
f

array([['hey', 'hey'],
       ['hey', 'hey'],
       ['hey', 'hey']], dtype='<U6')

In [ ]:
f.fill(4)
f.dtype="int"
f

array([[4616189618054758400, 4616189618054758400, 4616189618054758400,
        4616189618054758400, 4616189618054758400, 4616189618054758400],
       [4616189618054758400, 4616189618054758400, 4616189618054758400,
        4616189618054758400, 4616189618054758400, 4616189618054758400],
       [4616189618054758400, 4616189618054758400, 4616189618054758400,
        4616189618054758400, 4616189618054758400, 4616189618054758400]])

In [ ]:
f.fill(4)
f.dtype="float"
f

array([[2.e-323, 2.e-323, 2.e-323, 2.e-323, 2.e-323, 2.e-323],
       [2.e-323, 2.e-323, 2.e-323, 2.e-323, 2.e-323, 2.e-323],
       [2.e-323, 2.e-323, 2.e-323, 2.e-323, 2.e-323, 2.e-323]])

In [ ]:
#linear space # divide range blw 10 and 20 into 10 equal spaces
l=np.linspace(10,20,10)
l

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [ ]:
l=np.linspace(10,20,15)
l

array([10.        , 10.71428571, 11.42857143, 12.14285714, 12.85714286,
       13.57142857, 14.28571429, 15.        , 15.71428571, 16.42857143,
       17.14285714, 17.85714286, 18.57142857, 19.28571429, 20.        ])

In [ ]:
# creating array with arange() similar to range
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
a=np.arange(25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
a=np.arange(25,100,2)
a

array([25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57,
       59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91,
       93, 95, 97, 99])

In [ ]:
a=np.arange(50,10,-5)
a

array([50, 45, 40, 35, 30, 25, 20, 15])

In [ ]:
# converting existing array into 2d array
a=np.arange(5)
len(a)
a.reshape(1,5)

array([[0, 1, 2, 3, 4]])

In [ ]:
a=np.arange(12)
len(a)
a.reshape(1,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [ ]:
a=np.arange(12)
len(a)
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a=np.arange(12)
len(a)
a.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
a=np.arange(12)
len(a)
a.reshape(12,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

#### random()
  - used to generate random integers in a range 
  - random.randint()

In [4]:
import numpy as np 
np.random.randint(10)                     # value blw 0 and 10

5

# np.random.randint(lwr,uper,number of values to print)

In [6]:
np.random.randint(15,30,5)

array([24, 21, 26, 29, 27])

## multiple random values results in array

In [10]:
l,u=int(input()),int(input())
r1=np.random.randint(l,u,8)
r1.reshape(4,2)

12 
56


array([[50, 21],
       [39, 33],
       [44, 38],
       [24, 22]])

## gives lower*upper float values

In [15]:
np.random.random((2,5))  # tuple 

array([[0.0918011 , 0.06632182, 0.70751822, 0.73834564, 0.18487507],
       [0.02343304, 0.80185991, 0.3189692 , 0.59063818, 0.39068464]])

In [16]:
np.random.rand(4,5)   # syntax   blw 0 & 1

array([[0.46045554, 0.14654427, 0.70244131, 0.83837552, 0.20313964],
       [0.51496906, 0.39991364, 0.97552185, 0.59678515, 0.80424695],
       [0.94721365, 0.01307162, 0.5664891 , 0.98010891, 0.78055192],
       [0.3783024 , 0.83271568, 0.39518257, 0.14006144, 0.41140893]])

In [17]:
np.random.randn(4,5)   # blw -1 & 1

array([[ 0.96454233, -2.11427392, -0.54117304,  0.54680329, -0.18186089],
       [-1.26722079,  0.32737085, -0.13567469,  0.74100989, -0.70233423],
       [-0.30484726,  0.46823086, -0.480261  , -1.47698355, -1.37337176],
       [ 0.69571378, -1.11650515, -0.98534033, -1.12743727, -1.18871288]])

In [19]:
np.linspace(12,2)

array([12.        , 11.79591837, 11.59183673, 11.3877551 , 11.18367347,
       10.97959184, 10.7755102 , 10.57142857, 10.36734694, 10.16326531,
        9.95918367,  9.75510204,  9.55102041,  9.34693878,  9.14285714,
        8.93877551,  8.73469388,  8.53061224,  8.32653061,  8.12244898,
        7.91836735,  7.71428571,  7.51020408,  7.30612245,  7.10204082,
        6.89795918,  6.69387755,  6.48979592,  6.28571429,  6.08163265,
        5.87755102,  5.67346939,  5.46938776,  5.26530612,  5.06122449,
        4.85714286,  4.65306122,  4.44897959,  4.24489796,  4.04081633,
        3.83673469,  3.63265306,  3.42857143,  3.2244898 ,  3.02040816,
        2.81632653,  2.6122449 ,  2.40816327,  2.20408163,  2.        ])

### Accessing the array elements
  - using index.
  - index is 3 types.
  - +ve indexing ,-ve indexing and fancy indexing.
    - +ve from left to right (starts at 0)
    - -ve from right to left (starts at -1)
    - fancy: condition based index

In [28]:
t=np.random.randint(50,200,25).reshape(5,-1)
t

array([[126,  68, 182, 119, 106],
       [172, 122,  88, 120,  80],
       [190, 164,  72, 116, 115],
       [169, 139, 115, 182, 122],
       [193, 150, 199, 164,  84]])

In [32]:
l=np.arange(50,100,5).reshape(-1,5)
l

array([[50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

## accesing the array elements

In [34]:
l[:]

array([[50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [35]:
l[::]

array([[50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [36]:
l[::-1]

array([[75, 80, 85, 90, 95],
       [50, 55, 60, 65, 70]])

In [38]:
t[::2]

array([[126,  68, 182, 119, 106],
       [190, 164,  72, 116, 115],
       [193, 150, 199, 164,  84]])

In [39]:
t[0]

array([126,  68, 182, 119, 106])

In [43]:
t[:,1:4]             # in hole array prints this range 

array([[ 68, 182, 119],
       [122,  88, 120],
       [164,  72, 116],
       [139, 115, 182],
       [150, 199, 164]])

In [41]:
t

array([[126,  68, 182, 119, 106],
       [172, 122,  88, 120,  80],
       [190, 164,  72, 116, 115],
       [169, 139, 115, 182, 122],
       [193, 150, 199, 164,  84]])

### to print odd number in t[:,1:4]  

In [46]:
e=t[:,1:4]               
for i in e:
  for j in i:
    if j%2==1:
      print(j)  

119
139
115
199


In [48]:
t[1:4,1:4]

array([[122,  88, 120],
       [164,  72, 116],
       [139, 115, 182]])

In [55]:
t[::2,::2]

array([[126, 182, 106],
       [190,  72, 115],
       [193, 199,  84]])

### transpose of a matrix

In [56]:
t.transpose()

array([[126, 172, 190, 169, 193],
       [ 68, 122, 164, 139, 150],
       [182,  88,  72, 115, 199],
       [119, 120, 116, 182, 164],
       [106,  80, 115, 122,  84]])

## fancy indexing

In [63]:
t<130                #boolean type

array([[ True,  True, False,  True,  True],
       [False,  True,  True,  True,  True],
       [False, False,  True,  True,  True],
       [False, False,  True, False,  True],
       [False, False, False, False,  True]])

In [58]:
t

array([[126,  68, 182, 119, 106],
       [172, 122,  88, 120,  80],
       [190, 164,  72, 116, 115],
       [169, 139, 115, 182, 122],
       [193, 150, 199, 164,  84]])

In [62]:
t[t<130]

array([126,  68, 119, 106, 122,  88, 120,  80,  72, 116, 115, 115, 122,
        84])

# Scientific Computations on arrays

### Perform all the arthmetic operations on both arrays

In [64]:
print(t+t)

[[252 136 364 238 212]
 [344 244 176 240 160]
 [380 328 144 232 230]
 [338 278 230 364 244]
 [386 300 398 328 168]]


In [65]:
print(t-t)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [66]:
print(t*t)

[[15876  4624 33124 14161 11236]
 [29584 14884  7744 14400  6400]
 [36100 26896  5184 13456 13225]
 [28561 19321 13225 33124 14884]
 [37249 22500 39601 26896  7056]]


In [75]:
p=np.arange(10).reshape(2,-1)
p

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [73]:
l

array([[50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [76]:
p+l

array([[ 50,  56,  62,  68,  74],
       [ 80,  86,  92,  98, 104]])

In [77]:
l-p

array([[50, 54, 58, 62, 66],
       [70, 74, 78, 82, 86]])

In [78]:
l*p

array([[  0,  55, 120, 195, 280],
       [375, 480, 595, 720, 855]])

In [79]:
l//p

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


array([[ 0, 55, 30, 21, 17],
       [15, 13, 12, 11, 10]])

In [82]:
p.mean()

4.5

In [85]:
p.min()

0

In [86]:
p.max()

9

In [87]:
p

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [88]:
p.sum()

45

In [89]:
sum(p)

array([ 5,  7,  9, 11, 13])

In [90]:
sum(l)

array([125, 135, 145, 155, 165])

In [91]:
l

array([[50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [92]:
t

array([[126,  68, 182, 119, 106],
       [172, 122,  88, 120,  80],
       [190, 164,  72, 116, 115],
       [169, 139, 115, 182, 122],
       [193, 150, 199, 164,  84]])

In [93]:
sum(t)

array([850, 643, 656, 701, 507])

In [94]:
t


array([[126,  68, 182, 119, 106],
       [172, 122,  88, 120,  80],
       [190, 164,  72, 116, 115],
       [169, 139, 115, 182, 122],
       [193, 150, 199, 164,  84]])

In [95]:
t[2][2]

72

In [96]:
t[:][0].sum()

601

In [98]:
t[:][0]


array([126,  68, 182, 119, 106])

In [101]:
t[:,0].sum()

850

In [100]:
t[:,0]

array([126, 172, 190, 169, 193])

## logorithms and exponential

In [102]:
np.log(1)

0.0

In [103]:
np.log(10)

2.302585092994046

In [104]:
np.log(0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [107]:
np.log10(10)

1.0

In [108]:
np.exp(1)

2.718281828459045

In [109]:
np.exp(np.log(1))

1.0

In [110]:
np.exp(np.log(5))

4.999999999999999

In [111]:
np.log(np.exp(1))

1.0

In [117]:
np.log(np.exp(5))

5.0

# vectorised functions in numpy

In [148]:
def greater(a,b):
  if a>b:
    print(a)
  else:
    print(b)
new=[]
for i,j in zip(a,b):
  if i>j:
    new.append(i)
  elif j>i:
    new.append(j)
new

[4, 5, 8]

In [121]:
greater([2,4,5],[4,5,8])

[4, 5, 8]


In [122]:
greater(3,4)

4


In [129]:
max([7,9,5],[7,9,8])

[7, 9, 8]

In [132]:
a,b=[2,4,5],[4,5,8]
new=[]
for i,j in zip(a,b):
  if i>j:
    new.append(i)
  elif j>i:
    new.append(j)
new

[4, 5, 8]

In [150]:
greater([6,9,4],[7,9,8])

[7, 9, 8]


In [149]:
greater(3,4)

4
